# Usando a imagem oficial do Nginx
FROM nginx:alpine

# Copiando os arquivos de frontend para a pasta padrão do Nginx
COPY ./client /usr/share/nginx/html

# Expondo a porta 80 (padrão do Nginx)
EXPOSE 80

# Configurando o comando para rodar o Nginx em segundo  plano
CMD ["nginx", "-g", "daemon off;"]
