version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile  
    container_name: backend
    environment:
      - DB_HOST=mariadb
      - DB_USER=root
      - DB_PASSWORD=fatec
      - DB_NAME=crud
    ports:
      - "3000:3000"
    depends_on:
      - mariadb
    networks:
      - crudnet
    restart: unless-stopped 

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: fatec
      MYSQL_DATABASE: crud
      MYSQL_USER: root  
      MYSQL_PASSWORD: fatec
    ports:
      - "3308:3306"
    networks:
      - crudnet
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s
    restart: unless-stopped

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile  # Especifica explicitamente o Dockerfile para evitar confusão
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - crudnet
    depends_on:
      - backend
    restart: unless-stopped  # Política de reinício para garantir alta disponibilidade

networks:
  crudnet:
    driver: bridge  # Mantém a rede de containers isolada

volumes:
  mariadb_data:
    driver: local  # Volume persistente para o banco de dados MariaDB
